const sampleProducts = [
  {
    name: "Smartphone X12",
    price: 799.99,
    description: "A high-end smartphone with excellent camera and performance.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.5,
    category: "Electronics",
    ratingCount: 1250,
  },
  {
    name: "Wireless Headphones Pro",
    price: 199.99,
    description: "Noise-cancelling wireless headphones with superior sound quality.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.7,
    category: "Accessories",
    ratingCount: 987,
  },
  {
    name: "Gaming Laptop GX500",
    price: 1499.99,
    description: "A gaming laptop with the latest GPU and ultra-fast processing power.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.8,
    category: "Computers",
    ratingCount: 540,
  },
  {
    name: "4K Smart TV",
    price: 899.99,
    description: "A 55-inch smart TV with 4K resolution and HDR support.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.6,
    category: "Home Entertainment",
    ratingCount: 750,
  },
  {
    name: "Running Shoes UltraBoost",
    price: 129.99,
    description: "Comfortable running shoes designed for long-distance runners.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.3,
    category: "Footwear",
    ratingCount: 320,
  },
  {
    name: "Stainless Steel Water Bottle",
    price: 24.99,
    description: "Durable and reusable water bottle with 1L capacity.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.9,
    category: "Lifestyle",
    ratingCount: 1500,
  },
  {
    name: "Ergonomic Office Chair",
    price: 249.99,
    description: "A chair designed for maximum comfort and productivity.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.4,
    category: "Furniture",
    ratingCount: 670,
  },
  {
    name: "Professional DSLR Camera",
    price: 1199.99,
    description: "A high-resolution camera suitable for professionals and enthusiasts.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.8,
    category: "Photography",
    ratingCount: 920,
  },
  {
    name: "Wireless Mouse and Keyboard Combo",
    price: 59.99,
    description: "A wireless keyboard and mouse set with ergonomic design.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.2,
    category: "Accessories",
    ratingCount: 450,
  },
  {
    name: "Electric Toothbrush",
    price: 89.99,
    description: "A rechargeable toothbrush with multiple cleaning modes.",
    imageUrl: "https://via.placeholder.com/150",
    rating: 4.6,
    category: "Personal Care",
    ratingCount: 600,
  },
];

module.exports = sampleProducts;
